version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: movie_booking
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 4444:5432